# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.02]
  pull_request:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.02]

concurrency: CI-2.02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-dev libxslt-dev libxslt1-dev python3-dev python3-lxml libxml2-utils
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: xmllint
        run: xmllint --schema codelist.xsd --noout xml/*

      - name: flake8 lint
        run: flake8 --exclude=pyenv,pyenv3 --ignore E501

      - name: Build and test
        run: |
          ./gen.sh
          pytest tests

  update-validator-codelists:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]' }}
    steps:
      - name: 'Trigger update of Validator Codelists repository'
        run: |
          curl  -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.IATI_BOT_PAT }}' \
          -X POST https://api.github.com/repos/IATI/IATI-Validator-Codelists/actions/workflows/push-CI.yml/dispatches \
          --data '{"ref": "version-2.02", "inputs": { "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}'

  update-rule-tracker:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]' }} # only push to the rule tracker on PUSH
    steps:
      - name: 'Trigger update of rule tracker repo .csv'
        run: |
          curl -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.IATI_BOT_PAT }}' \
          -X POST https://api.github.com/repos/IATI/validator-rule-tracker/dispatches \
          --data '{"event_type": "update", "client_payload": { "resourceName": "codelists", "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}'

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
