# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.03]
  pull_request:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.03]

concurrency: CI-2.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-dev libxslt-dev libxslt1-dev python3-dev python3-lxml libxml2-utils
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: xmllint
        run: xmllint --schema codelist.xsd --noout xml/*

      - name: flake8 lint
        run: flake8 --exclude=pyenv,pyenv3 --ignore E501

      - name: Build and test
        run: |
          ./gen.sh
          pytest tests

  update-validator-codelists:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]' }}
    steps:
      - name: 'Trigger update of Validator Codelists repository'
        run: |
          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.IATI_BOT_PAT }}' \
          -X POST https://api.github.com/repos/IATI/IATI-Validator-Codelists/actions/workflows/dispatch-CI.yaml/dispatches \
          --data '{"ref": "version-2.03", "inputs": { "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}' \
          --output curl_out.txt \
          --silent )
          echo $HTTP_CODE
          if [[ $HTTP_CODE != '204' ]] ; then
            echo "Reponse is not 204, check error logs"
            cat curl_out.txt
            exit 1
          fi

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
