# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI_version-2.01

env:
  DEV_DEFAULT_KEY: ${{ secrets.DEV_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
  VERSION: 2.01

on:
  push:
    branches: [version-2.01, v2.01/validatorCodelist]
  pull_request:
    branches: [version-2.01]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: xmllint
        run: xmllint --schema codelist.xsd --noout xml/*

      - name: flake8 lint
        run: flake8 --exclude=pyenv,pyenv3 --ignore E501

  cache-codelist-rules:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
    steps:
      - uses: actions/checkout@v2

      - name: POST codelist_rules.json to redis-cacher
        run: |
          curl --location --request POST 'https://func-iati-redis-cacher-dev.azurewebsites.net/api/pvt/cache?key=codelistRules'$VERSION \
          --header 'x-functions-key: '$DEV_DEFAULT_KEY \
          --header 'Content-Type: application/json' \
          --data-binary '@./codelist_rules.json'